version: '3.8'

services:
  app1:
    image: devsidnei/quiz-react-app:latest
    expose:
      - "80"
    labels:
      - "traefik.http.routers.app1.rule=Host(`app1.integrab2b.com.br`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls=true"
      - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
      - "traefik.http.services.app1.loadbalancer.server.port=80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
